name: Sync to MediaWiki
on:
  push:
    branches: [ main ]
jobs:
  push-wiki:
    runs-on: ubuntu-22.04   # <= pin to 22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install git-remote-mediawiki
        run: |
          sudo apt-get update
          sudo apt-get install -y libmediawiki-api-perl libdatetime-format-iso8601-perl
          # Download the script directly from GitHub
          echo "Downloading git-remote-mediawiki..."
          curl -fsSL https://raw.githubusercontent.com/git/git/master/contrib/mw-to-git/git-remote-mediawiki.perl -o /tmp/git-remote-mediawiki
          # Verify it downloaded
          if [ ! -f /tmp/git-remote-mediawiki ]; then
            echo "ERROR: Failed to download script"
            exit 1
          fi
          echo "First line of script:"
          head -n 1 /tmp/git-remote-mediawiki
          # Install it
          sudo mv /tmp/git-remote-mediawiki /usr/local/bin/git-remote-mediawiki
          sudo chmod +x /usr/local/bin/git-remote-mediawiki
          # Verify installation
          echo "Verifying installation..."
          ls -l /usr/local/bin/git-remote-mediawiki
          which git-remote-mediawiki || echo "Warning: not in PATH, but should work anyway"

      - name: Preflight API check
        env:
          WIKI_API: ${{ secrets.WIKI_API }}
        run: curl -fsSL "$WIKI_API?action=query&meta=siteinfo&format=json" >/dev/null

      - name: Push to MediaWiki
        env:
          WIKI_USER: ${{ secrets.WIKI_USER }}
          WIKI_PASS: ${{ secrets.WIKI_PASS }}
          WIKI_API:  ${{ secrets.WIKI_API }}
        run: |
          git config user.name "GitHub CI"
          git config user.email "ci@example.org"
          scheme="${WIKI_API%%://*}"
          rest="${WIKI_API#*://}"
          if [ "$scheme" = "$WIKI_API" ] || [ -z "$scheme" ]; then
            scheme="https"
          fi
          rest="${rest%%\?*}"
          rest="${rest%%#*}"
          rest="${rest%/api.php}"
          rest="${rest%/index.php}"
          rest="${rest%/}"
          git remote add wiki "mediawiki::${scheme}://${WIKI_USER}:${WIKI_PASS}@${rest}"
          git push wiki HEAD
