name: Sync to MediaWiki
on:
  push:
    branches: [ main ]
jobs:
  push-wiki:
    runs-on: ubuntu-22.04   # <= pin to 22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install git-remote-mediawiki
        run: |
          sudo apt-get update
          sudo apt-get install -y libmediawiki-api-perl libdatetime-format-iso8601-perl
          # Download the complete Git-Mediawiki repository
          echo "Downloading Git-Mediawiki..."
          cd /tmp
          git clone https://github.com/Git-Mediawiki/Git-Mediawiki.git
          cd Git-Mediawiki
          # Install the Perl module
          echo "Installing Git::Mediawiki module..."
          sudo mkdir -p /usr/local/share/perl/5.34.0/Git
          sudo cp -r Git/Mediawiki.pm /usr/local/share/perl/5.34.0/Git/
          # Install the git-remote-mediawiki script
          echo "Installing git-remote-mediawiki script..."
          sudo cp git-remote-mediawiki /usr/local/bin/git-remote-mediawiki
          sudo chmod +x /usr/local/bin/git-remote-mediawiki
          # Verify installation
          echo "Verifying installation..."
          ls -l /usr/local/bin/git-remote-mediawiki
          ls -l /usr/local/share/perl/5.34.0/Git/Mediawiki.pm

      - name: Preflight API check
        env:
          WIKI_API: ${{ secrets.WIKI_API }}
        run: curl -fsSL "$WIKI_API?action=query&meta=siteinfo&format=json" >/dev/null

      - name: Push to MediaWiki
        env:
          WIKI_USER: ${{ secrets.WIKI_USER }}
          WIKI_PASS: ${{ secrets.WIKI_PASS }}
          WIKI_API:  ${{ secrets.WIKI_API }}
        run: |
          git config user.name "GitHub CI"
          git config user.email "ci@example.org"
          # Extract base URL from WIKI_API
          scheme="${WIKI_API%%://*}"
          rest="${WIKI_API#*://}"
          if [ "$scheme" = "$WIKI_API" ] || [ -z "$scheme" ]; then
            scheme="https"
          fi
          rest="${rest%%\?*}"
          rest="${rest%%#*}"
          rest="${rest%/api.php}"
          rest="${rest%/index.php}"
          rest="${rest%/}"
          # Configure credentials via git config (not in URL)
          git config --global mediawiki.username "$WIKI_USER"
          git config --global mediawiki.password "$WIKI_PASS"
          # Add remote without credentials in URL
          git remote add wiki "mediawiki::${scheme}://${rest}"
          git push wiki main:master
