name: Sync to MediaWiki
on:
  push:
    branches: [ main ]
jobs:
  push-wiki:
    runs-on: ubuntu-22.04   # <= pin to 22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install git-remote-mediawiki
        run: |
          sudo apt-get update
          sudo apt-get install -y libmediawiki-api-perl libdatetime-format-iso8601-perl
          curl -o git-remote-mediawiki.perl https://raw.githubusercontent.com/git/git/master/contrib/mw-to-git/git-remote-mediawiki.perl
          chmod +x git-remote-mediawiki.perl
          sudo cp git-remote-mediawiki.perl /usr/local/bin/git-remote-mediawiki

      - name: Preflight API check
        env:
          WIKI_API: ${{ secrets.WIKI_API }}
        run: curl -fsSL "$WIKI_API?action=query&meta=siteinfo&format=json" >/dev/null

      - name: Push to MediaWiki
        env:
          WIKI_USER: ${{ secrets.WIKI_USER }}
          WIKI_PASS: ${{ secrets.WIKI_PASS }}
          WIKI_API:  ${{ secrets.WIKI_API }}
        run: |
          git config user.name "GitHub CI"
          git config user.email "ci@example.org"
          scheme="${WIKI_API%%://*}"
          rest="${WIKI_API#*://}"
          if [ "$scheme" = "$WIKI_API" ] || [ -z "$scheme" ]; then
            scheme="https"
          fi
          rest="${rest%%\?*}"
          rest="${rest%%#*}"
          rest="${rest%/api.php}"
          rest="${rest%/index.php}"
          rest="${rest%/}"
          git remote add wiki "mediawiki::${scheme}://${WIKI_USER}:${WIKI_PASS}@${rest}"
          git push wiki HEAD
