name: Sync to MediaWiki
on:
  push:
    branches: [ main ]
jobs:
  push-wiki:
    runs-on: ubuntu-22.04   # <= pin to 22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install git-remote-mediawiki
        run: |
          sudo apt-get update
          sudo apt-get install -y git-mediawiki

      - name: Preflight API check
        env:
          WIKI_API: ${{ secrets.WIKI_API }}
        run: curl -fsSL "$WIKI_API?action=query&meta=siteinfo&format=json" >/dev/null

      - name: Push to MediaWiki
        env:
          WIKI_USER: ${{ secrets.WIKI_USER }}
          WIKI_PASS: ${{ secrets.WIKI_PASS }}
          WIKI_API:  ${{ secrets.WIKI_API }}
        run: |
          git config user.name "GitHub CI"
          git config user.email "ci@example.org"
          git remote add wiki "mediawiki::https://${WIKI_USER}:${WIKI_PASS}@${WIKI_API#https://}"
          git push wiki HEAD
